services:

  cicd_test_project:
    build: .
    container_name: test_cicd
    ports:
      - "50051:50051"
    networks:
      - cicd

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - cicd
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=photos
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  cicd:
    driver: bridge

volumes:
  db:
    driver: local
  minio_data:
    driver: local