definitions:
  main.UrlRes:
    properties:
      minio_url:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /media:
    post:
      consumes:
      - application/json
      description: Through this api front-ent can upload photo and get the link to
        the photo.
      parameters:
      - description: Image
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UrlRes'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Upload Photo
      tags:
      - MEDIA
swagger: "2.0"
