name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  SERVER_USERNAME: ubuntu
  SERVER_IP: 52.28.87.185
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
         script: |
            if [ ! -d "amaliyot16/cicd/lesson_ci_cd" ]; then
              mkdir -p amaliyot16/cicd/lesson_ci_cd
              git clone git@github.com:xadichamahkamova/amaliyot16.git
            fi
            cd amaliyot16/cicd/lesson_ci_cd
            docker compose down || true
            git pull origin main
            docker compose up --build -d

          script_stop: true
          timeout: 200s
